name: Build and Push to GitLab Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Adjust this to the branch you want to trigger the workflow on
    paths:
      - 'front-end/peer-prep'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitLab Container Registry
      run: docker login registry.gitlab.com -u ${{ secrets.GITLAB_USERNAME }} -p ${{ secrets.DOCKER}}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1     
      
    - name: Build and push        
      uses: docker/build-push-action@v2
      with: 
        context: front-end/peer-prep
        file: ./front-end/peer-prep/Dockerfile          
        push: true
        tags: registry.gitlab.com/peerprepgroup51sem1y2023/docker/frontend:latest
    
